FROM java:8
VOLUME /tmp
ADD target/ZuulProxy-0.0.1-SNAPSHOT.jar zuul.jar
EXPOSE 9000
RUN bash -c 'touch /zuul.jar'
ENTRYPOINT ["java", "-Xmx80m", "-Djava.security.egd=file:/dev/./urandom","-jar","/zuul.jar"]